#!/bin/sh

print_help() {
	printf -- 'Help\n\n'
	printf -- 'Arguments:\n'
	printf -- '-h for help\n'
	printf -- '-gm to generate modlist\n'
	printf -- '-dm to download all mods from modlist\n'
	printf -- '\nWarning\n'
	printf -- '-dm removes all the mods before downloading from the modlist\n'
}

generate_modlist() {
	printf '# Mod list\n\n' > mod-list.md

	packwiz list | while read -r line
	do
		printf -- "- $line\n" >> mod-list.md
	done
}

download_modlist() {
	[ -d 'mods' ] && rm -r mods

	if ! [ -f "mod-list.$1.txt" ]
	then
		printf "mod-list.$1.txt file not found\n"

		exit 1
	fi

	packwiz refresh >> /dev/null 2>&1

	cat "mod-list.$1.txt" | while read -r line
	do
		packwiz "$1" add -y "$line"
	done
}

if [ -z "$(command -v packwiz)" ]
then
	printf 'Packwiz not found\n'

	exit 1
fi

if ! [ -f 'pack.toml' ]
then
	printf 'Modpack not found\n'

	exit 1
fi

if [ -z "$1" ] || [ "$1" = '-h' ]
then
	print_help
elif [ "$1" = '-gm' ]
then
	generate_modlist
elif [ "$1" = '-dm' ]
then
	if [ -z "$2" ]
	then
		printf 'Provider not specified\n'

		exit 1
	fi

	download_modlist "$2"
fi
