#!/bin/sh

print_help() {
	printf -- 'Help\n\n'
	printf -- 'Arguments:\n'
	printf -- '-h for help\n'
	printf -- '-gm to generate modlist\n'
	printf -- '-dm to download all mods from modlist\n'
	printf -- '\nWarning\n'
	printf -- '-dm removes all the mods before downloading from the modlist\n'
}

generate_modlist() {
	printf '# Mod list\n\n' > mod-list.md

	packwiz list | while read -r line
	do
		printf -- "- $line\n" >> mod-list.md
	done
}

download_modlist() {
	[ -d 'mods' ] && rm -r mods

	packwiz refresh >> /dev/null 2>&1

	cat download-list/mods.cf.txt | while read -r line
	do
		printf 'Mod link: %s\n' "$line"

		packwiz cf add -y "$line"
	done

	cat download-list/mods.mr.txt | while read -r line
	do
		printf 'Mod link: %s\n' "$line"

		packwiz mr add -y "$line"
	done
}

if [ -z "$(command -v packwiz)" ]
then
	printf 'Packwiz not found\n'

	exit 1
fi

if ! [ -f 'pack.toml' ]
then
	printf 'Modpack not found\n'

	exit 1
fi

if [ -z "$1" ] || [ "$1" = '-h' ]
then
	print_help
elif [ "$1" = '-gm' ]
then
	generate_modlist
elif [ "$1" = '-dm' ]
then
	download_modlist
fi
