#!/bin/sh

if [ -z "$(command -v rclone)" ]
then
	printf 'Rclone not found\n'

	exit 1
fi

if [ -z "$1" ]
then
	rclone copyto ~/.config/rclone/rclone.conf unencrypted-drive:rclone.conf

	rclone sync ~/.local/share/wiki encrypted-drive:wiki
elif [ "$1" = "--force-reverse-sync" ]
then
	rclone copyto unencrypted-drive:rclone.conf ~/.config/rclone/rclone.conf

	rclone sync encrypted-drive:wiki ~/.local/share/wiki
fi
